version: '3'

services:
  bitcoin-jvm:
    image: quarkus/bitcoin-jvm:latest
    build:
      context: ./
      dockerfile: src/main/docker/Dockerfile.${QUARKUS_MODE:-jvm}
    environment:
      QUARKUS_DATASOURCE_URL: jdbc:postgresql://postgres-bitcoin:5432/postgres?currentSchema=bitcoin
    networks:
      - bitcoin-network
    ports:
      - 8080:8080
    depends_on:
      - postgresql-bitcoin

  postgres-bitcoin:
    image: postgres:16.3
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - ./opt/docker-data:/var/lib/postgresql/data
    networks:
      - bitcoin-network

networks:
  bitcoin-network:
    driver: bridge
