version: '3'

services:
  bitcoin-jvm:
    image: quarkus/bitcoin-jvm:latest
    build:
      context: ./
      dockerfile: src/main/docker/Dockerfile.${QUARKUS_MODE:-jvm}
    environment:
      # QUARKUS_DATASOURCE_URL: jdbc:postgresql://bitcoin-postgresql:5432/postgres?currentSchema=bitcoin
      QUARKUS_DATASOURCE_URL: jdbc:postgresql://bitcoin-postgresql:5432/postgres
    networks:
      - bitcoin-network
    ports:
      - 8080:8080
    depends_on:
      - bitcoin-postgresql

  bitcoin-postgresql:
    image: postgres:16.3
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5433:5432
    volumes:
      - ./opt/docker-data:/var/lib/postgresql/data
      - ./src/main/resources/script.sql:/docker-entrypoint.initdb.d/script.sql
    networks:
      - bitcoin-network

networks:
  bitcoin-network:
    driver: bridge
